midea-lan/midea-local

README.md

Wanted to try out this library to see if I could send commands to my device. Was a little confused as to where to start, so I am sharing my first steps for anyone coming after.
Notes:
* I wasn't able to get the key and token from the `cloud` module. Would be good to add a section for that
* `devices.device_selector` worked for me after getting around #2 and #3 but the attributes did not reflect the state properly and `set_temperature_target` did not change anything on the device.

Add some hints on how to get started

---

.devcontainer/devcontainer.json
.vscode/tasks.json
requirements.txt

Unified #13 , #14 and task to build pkg

Multiple dev improvements

---

midealocal/message.py

Started introducing typing in the library.
- message.py

chore: typing part 3

---

midealocal/device.py
midealocal/message.py

Started introducing typing in the library.
- device.py
Few fixes for 
- message.py

chore: typing part 4

---

midealocal/device.py
midealocal/devices/c3/message.py

https://github.com/wuwentao/midea_ac_lan/pull/22/

Fix temperature out of range heat pump

---

midealocal/devices/fd/__init__.py
midealocal/devices/fd/message.py

Draft because of a issue with `self.fan_speed`

chore: typing fd

---

.vscode/launch.json
midealocal/cloud.py
tests/cli_test.py
tests/cloud_test.py

chore(cloud)!: rename MSmartHome

---

midealocal/cloud.py

Keep up to the first 5 characters  for cloud redact

chore(cloud): keep up the first 5 characters for cloud redact

---

midealocal/devices/b3/message.py

support new X00 body for B3 device
fix https://github.com/wuwentao/midea_ac_lan/issues/505

feat(b3): support new X00 body for B3 device

---

midealocal/devices/c3/__init__.py
midealocal/devices/c3/message.py
tests/devices/c3/device_c3_test.py

1. remove unsupported query, as C3 device not response to  these query.
2. add eco body parse

chore(c3): remove unsupported query and eco body parse

---

midealocal/devices/cf/__init__.py
midealocal/devices/cf/message.py

add defrost and freeze for CF device
fix https://github.com/wuwentao/midea_ac_lan/issues/462

feat(cf): add defrost and freeze for CF device

---

midealocal/devices/e6/__init__.py
midealocal/devices/e6/message.py

- Add cold water single/dot control attributes and methods
- Add climate compensation mode support
- Update message handling for new features

feat(e6): add cold water and climate compensation features

---

midealocal/devices/e3/__init__.py

issue: https://github.com/wuwentao/midea_ac_lan/issues/517

fix(e3): input target_temperature should be float

---

midealocal/devices/c3/__init__.py
midealocal/devices/c3/message.py

same as https://github.com/midea-lan/midea-local/pull/359
https://github.com/midea-lan/midea-local/pull/358

chore(c3): input temperature should be float

---

midealocal/devices/e6/__init__.py
midealocal/devices/e6/message.py

same as https://github.com/midea-lan/midea-local/pull/361
https://github.com/midea-lan/midea-local/pull/359
https://github.com/midea-lan/midea-local/pull/358

fix(e6): input temperature should be float

---

midealocal/devices/e2/__init__.py
midealocal/devices/e2/message.py

try to fix https://github.com/wuwentao/midea_ac_lan/issues/539

fix(e2): temperature should be float

---

midealocal/devices/e3/__init__.py
midealocal/devices/e3/message.py

fix https://github.com/wuwentao/midea_ac_lan/issues/543

fix(e3): temperature should be float

---

midealocal/devices/cd/__init__.py
midealocal/devices/cd/message.py

fix https://github.com/wuwentao/midea_ac_lan/issues/551

fix(cd): parse CD device message error

---

midealocal/device.py
midealocal/devices/cd/__init__.py

1. move `get_dict_key_by_value` to parent `MideaDevice` Class
2. add `celsius_to_fahrenheit` and `fahrenheit_to_celsius` to parent `MideaDevice` Class

chore(cd): move common feature to parent MideaDevice Class

---

midealocal/device.py
midealocal/devices/ac/__init__.py
midealocal/devices/ac/message.py
midealocal/message.py
tests/device_test.py
tests/devices/ac/device_ac_test.py
tests/devices/ac/message_ac_test.py

1. ac device support airflow direction control
2. remove capabilities related code, as it only available for some AC device and not for all devices.
3. will check and confirm these capabilities related feature in future PR with more debug log and device support info

feat(ac): ac device support airflow direction control

---

midealocal/devices/a1/__init__.py

This allows one to set custom values for the default **modes** and **speeds** of a dehumidifier. The code was largely copied from other device classes with the `set_customize` method and modified to fit this use case. I tested it without issue on my device. 
For my use case, I was trying to modify the **modes** and **speeds** in HA to match those of the Midea 50 pt. Cube Dehumidifier with Built-in Pump (MAD50PS1QWT). However, this is applicable to any other dehumidifier that has different **modes** and **speeds** than the defaults. 
For the MAD50PS1QWT device, the valid custom configuration is:
`{ "speeds": {"40": "Low", "80": "High"}, "modes": {"1": "Manual", "2": "Continuous", "4": "Max"} }`
Generally, this custom configuration should be the same for all Midea Cube Dehumidifiers and …

feat(a1): allow customization of default modes and speeds for dehumidifiers

---

.github/workflows/lint-pr.yml

`grafana/pr-labeler-action@v0.1.0` can't works now.
remove id, parse PR title and add label

chore(ci): extract PR title and add labels

---

midealocal/devices/ac/__init__.py
midealocal/devices/ac/message.py

it shoud fix https://github.com/wuwentao/midea_ac_lan/issues/666 and https://github.com/wuwentao/midea_ac_lan/issues/685

fix(ac): fix ac device screen display on and off every 15 mins

---

midealocal/devices/ac/__init__.py
midealocal/devices/ac/message.py

try to parse capability query respone b5 message in # https://github.com/wuwentao/midea_ac_lan/issues/673
still in draft status, just add these code for debug and confirm the result, and we can continue improve it with future test log and updates.

feat(ac): parse capability query respone b5 message
